name: Verify Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize Submodules
      run: git submodule update --init --recursive
    - name: Install tools
      run: |
        ./Embedded-Sharepoint/Scripts/install.sh -i
        sudo apt -y update
    - name: clean
      run: make clean
    - name: make leader
      run: make leader
    # Check that format was ran and has no errors
    - name: format-check
      run: make format-check
    # Apply format in case newline changes create tidy warnings (NOLINT comments change lines)
    - name: format
      run: make format
    # Check that tidy was ran and has no errors
    - name: tidy-check
      run: make tidy-check
