name: Verify Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize Submodules
      run: git submodule update --init --recursive
    - name: Install tools
      run: |
        ./Embedded-Sharepoint/Scripts/install.sh -i
        sudo apt -y update
    - name: clean
      run: make clean
    - name: make leader
      run: make leader
    # Run tidy and format and then tidy again in case format moves any NOLINTs to other lines, thus creating warnings/errors
    - name: tidy
      run: make tidy
    - name: format
      run: make format
    - name: tidy
      run: make tidy
